package rules
import com.example.demo.pojo.Employee
import com.example.demo.pojo.TicketPojo

function int testfun(int a) {
	int a1=a+1;
	return a1;
}

rule "rule for testing"
no-loop true
when 
 $t:TicketPojo()
 $e:Employee(Location==$t.getLocation && priority==testfun(1) ) from $t.empList
 //Employee(priority>$e.getPriority)
 then
 $t.setAssigned($e.getName());
  System.out.println($e.getName());
   System.out.println(testfun(1));
 end
 

/***********************New*****************************/
package rules

import com.info.ticket.rule.pojo.Ticket
import com.info.ticket.rule.pojo.User

dialect 'java'

rule "For Location And Category "
    dialect "java"
	when
    $p:Ticket()
    $e:User(location==$p.getLocation && department==$p.getCategory) from $p.empList
    then
     $p.setAssignee($e.getUsername());
     $p.setStatus("Assigned");
    
  
end
/***********************End********************************/
